// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValconLibrary.Data;

#nullable disable

namespace ValconLibrary.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20240517102206_FirstLastNameNotRequired")]
    partial class FirstLastNameNotRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValconLibrary.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("role");

                    b.Property<string>("Salt")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("salt");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            Email = "admin@valcon.com",
                            FirstName = "Valcon",
                            LastName = "Admin",
                            Password = "jB6d+fUEs8n2foX6Y9s5bL9AIDFMhQyCCpAUIRlMLMtJQ6DAWrTb2fEz5vPZNwXh49Ed0/Cr/H1MZgMQg4qAELwR+NZiaZMdk6l2ZBFaJGFZh6lvZdbGMrgcWOWeJvu85nXL7MqbMt+twGHGNWAExVh1h03VJ4DskJ7Rg1V10ubcNDp1tAE9oeqM7AqzCfvJo5W5u55dSIloGy26Rg+o2a3aTVE7COPId/ILrgF3s7xgCkeuF+Zp49AAuGqW5GduMDq0mr8BYReETyUVZUR+nplXvz4yI4cl1YGXUnH/kqAJCWtzrysZn5qA+8XO4nz3TmyDTRecutQtCzAQBPBjyA==",
                            Role = "Admin",
                            Salt = "KAGi+3WWvAdqZQ=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
