// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValconLibrary.Data;

#nullable disable

namespace ValconLibrary.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20240516111012_PasswordAndSaltCorrection")]
    partial class PasswordAndSaltCorrection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValconLibrary.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("role");

                    b.Property<string>("Salt")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("salt");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            Email = "admin@valcon.com",
                            FirstName = "Valcon",
                            LastName = "Admin",
                            Password = "P+03CZXQwPidLMjuoV7B26iBaL0PlwlfdHZz3cP4WTZuoAjZbe5MqJCtruLZnq0rQkxJ0eu/EaQq2FLQqEgdkdGXXrL6xwtnsH3bgMVvwaxMtAVyz1/hircUxg2xNgOi4CukRhUW/94BKkdVpXqbQHyue0cwWKd5jHY3Lv8xBqh0GxvFdMWYwHz28JS6Japbpm3nw0R/bFp96AKMCHDdSWrzhS/FLMvorMOgjPMjpxvPrsRXC8YacL6r469uxXWBwPhig1bgS5bixmVNsdPS/UT2lch6iKZHg6OpsmczpCgijPBCJe+CgSaPiz+Rp6jGDAJySIsNS2YQV5N6EVqaXA==",
                            Role = "Admin",
                            Salt = "UyJAAVU8Ah/WIw=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
