// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValconLibrary.Data;

#nullable disable

namespace ValconLibrary.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20240516094437_UserRoleAndAdmin")]
    partial class UserRoleAndAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValconLibrary.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("role");

                    b.Property<string>("Salt")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("salt");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            FirstName = "Valcon",
                            LastName = "Admin",
                            Password = "ZoG05mNx76EFRSOm9MeWuYFGOOZVo25EjQltikW5epDnkOwPRAY2fSxWrOhZGI0FJYSAgZNQe+LVHkQHKap4r8ADTDFpyxc9GaeKVHnMjz2tCheZ4PcyXsqdsILiiDbxsD/OFVtQxxQxEgOqUVNfZ07/zfd3/v6cVQ60H880UdLW+AhWtQ5WidhawvOD4tMRzl4j3V3n9DctzsSC0VtR6Ii+jLCsAPOejgcWSCYohOFjLhoAgA0iUHjMGgIrwyYNHGvHUnk1Mhtq0dvA4WVzjeX5BTM/xIpALgHtu+YLFGiEfwzQfBozgZpRyzCbc4WUcVcl1IIy1z2R54XSxWpCcg==",
                            Role = "Admin",
                            Salt = "HREjDgrlaXzC+A=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
